name: order_service

services:
  postgresql:
    container_name: order_service_postgresql
    image: postgres
    environment:
      POSTGRES_USER: order_service
      POSTGRES_PASSWORD: order_service
    restart: always
    volumes:
      - postgres:/data/postgres
    ports:
      - "5450:5432"
    networks:
      - orders

  redis:
    container_name: order_service_redis
    image: redis:latest
    environment:
      - REDIS_PASSWORD=order_service
      - REDIS_USER=order_password
      - REDIS_USER_PASSWORD=order_service
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis:/data/redis
    networks:
       - orders

volumes:
  postgres:
  redis:

networks:
  orders:
    driver: bridge